### ISSUE TITLE
will this work on 20.04

### ISSUE THREAD

**Issue by ugothmeex** [oliguo/Server-Certbot-XAMPP-Ubuntu#1]
will this work on 20.04.
planning to upgrade

**Comment by oliguo** [comment]
> will this work on 20.04.
> planning to upgrade

Yes, 20.04 it has pre-install snapd and you can install certbot by [snapd](https://certbot.eff.org/lets-encrypt/ubuntufocal-apache) ,

and the key command of my doc, it needs to relate _/opt/lampp/bin/apachectl_ 
` sudo certbot --apache-ctl /opt/lampp/bin/apachectl`

Reference: https://certbot.eff.org/docs/using.html#apache
```
--apache-ctl APACHE_CTL
                        Full path to Apache control script (default:
                        apache2ctl)
```

**Comment by oliguo** [comment]
> will this work on 20.04.
> planning to upgrade

Updated detail here below
### For 20.04 with snap
```
sudo apt-get install snapd -y
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo apt-get install python3-certbot-apache apache2-utils
```
