### ISSUE TITLE
VHost Config

### ISSUE THREAD

**Issue by Dysterkind** [oliguo/Server-Certbot-XAMPP-Ubuntu#2]
Hi, I am running Kubuntu 20.04 - installed certbot via snap.

Could you please be so kind and add detailed information how you set up the example vhost?

As I am currently struggeling to get certbot obtain the domainname given in /opt/lampp/etc/extra/httpd-vhosts.conf eg "newvhost.domain.com" (same name set in /etc/hotsts - 127.0.1.1 newvhost.domain.com)

> <VirtualHost *:80>
>     ServerAdmin mymail@here.com
>     DocumentRoot "/opt/lampp/htdocs/newsite"
>     ServerName newvhost.domain.com
>     ErrorLog "logs/newvhost.domain.com-error_log"
>     CustomLog "logs/newvhost.domain.com-access_log" common
> </VirtualHost>

Given certbot error is:
`sudo certbot --apache-ctl /opt/lampp/bin/apachectl`
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel):

Thank you in advance!

/D

**Comment by oliguo** [comment]
Dear Dysterkind,

May I know you uncomment the vhost.conf

```
sudo nano /opt/lampp/etc/httpd.conf
------------
# Virtual hosts
Include etc/extra/httpd-vhosts.conf
```

If yes and it still not work, how about trying the [ubuntu 16.04 way](https://github.com/oliguo/Server-Certbot-XAMPP-Ubuntu/blob/master/Ubuntu16.04/README.md) to do first, I didn't touch kubuntu before, maybe I will take time to try it on the virtualbox and let you know if any way I found.

**Comment by Dysterkind** [comment]
Dear Oliver,

I can confirm that said vhost.conf entry has been uncommented in /opt/lampp/etc/httpd.conf

In the meantime I got the certificate generation working - but with a lot of hands on:

Using --appache-ctl and +path and entering the URL to be certificated threw an error stating an invalid response from the URL - an attempt of using --webroot -w /opt/lampp/htdocs/newinstance instead of --apache-ctl generated a certificate only which I implemented into the vhost config - renewal is working fine too since the .pem's are located within the /etc/letsencrypt/live folder.

What I should mention that I am running Kubuntu 20.04 x64 with a fairly old LAMPP Version (5.5.19 x86) - the reason is needed compatibility for a quite old webapp.

/D
