### ISSUE TITLE
port 40?

### ISSUE THREAD

**Issue by ramsamba** [oliguo/Server-Certbot-XAMPP-Ubuntu#4]
hi guo

at this link, https://github.com/oliguo/Server-Certbot-XAMPP-Ubuntu#4-comment-all-ports-both-40-and-443-from-the-fileportsconf, it says port 40.

did you mean port 80 instead of port 40?

**Comment by oliguo** [comment]
Hi Ramsamba,

Thanks for the point out, sorry for miss typing, it is 80, not the 40.
